version: '3.9'

services:
  app:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    ports:
      - "8085:8085"
    restart: unless-stopped
    networks:
      - network
  postgres:
    image: postgres:15-alpine
    ports:
      - "5444:5432"
    volumes:
      - expression-vlm:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=expression_user
      - POSTGRES_PASSWORD=expression_password
      - POSTGRES_DB=expression_db
    networks:
      - network
networks:
  network:
    driver: bridge
volumes:
  expression-vlm:
