// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/task.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MiniTaskServiceClient is the client API for MiniTaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MiniTaskServiceClient interface {
	Solve(ctx context.Context, in *MiniTaskRequest, opts ...grpc.CallOption) (*MiniTaskResponse, error)
}

type miniTaskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMiniTaskServiceClient(cc grpc.ClientConnInterface) MiniTaskServiceClient {
	return &miniTaskServiceClient{cc}
}

func (c *miniTaskServiceClient) Solve(ctx context.Context, in *MiniTaskRequest, opts ...grpc.CallOption) (*MiniTaskResponse, error) {
	out := new(MiniTaskResponse)
	err := c.cc.Invoke(ctx, "/MiniTaskService/Solve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiniTaskServiceServer is the server API for MiniTaskService service.
// All implementations must embed UnimplementedMiniTaskServiceServer
// for forward compatibility
type MiniTaskServiceServer interface {
	Solve(context.Context, *MiniTaskRequest) (*MiniTaskResponse, error)
	mustEmbedUnimplementedMiniTaskServiceServer()
}

// UnimplementedMiniTaskServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMiniTaskServiceServer struct {
}

func (UnimplementedMiniTaskServiceServer) Solve(context.Context, *MiniTaskRequest) (*MiniTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Solve not implemented")
}
func (UnimplementedMiniTaskServiceServer) mustEmbedUnimplementedMiniTaskServiceServer() {}

// UnsafeMiniTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MiniTaskServiceServer will
// result in compilation errors.
type UnsafeMiniTaskServiceServer interface {
	mustEmbedUnimplementedMiniTaskServiceServer()
}

func RegisterMiniTaskServiceServer(s grpc.ServiceRegistrar, srv MiniTaskServiceServer) {
	s.RegisterService(&MiniTaskService_ServiceDesc, srv)
}

func _MiniTaskService_Solve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MiniTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniTaskServiceServer).Solve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MiniTaskService/Solve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniTaskServiceServer).Solve(ctx, req.(*MiniTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MiniTaskService_ServiceDesc is the grpc.ServiceDesc for MiniTaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MiniTaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MiniTaskService",
	HandlerType: (*MiniTaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Solve",
			Handler:    _MiniTaskService_Solve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/task.proto",
}
